sarroutbi/sarroutbi

README.md

Add some information about written articles to README.md

Update README.md with written articles

---

.wordlist.txt
README.md

Add other projects collaboration

---

.wordlist.txt
README.md

Include Special Projects repository collaboration

---

.wordlist.txt

Detail more deeply what tang-operator is for

---

.wordlist.txt
README.md

Detail more deeply what tang-operator is for (#21)

---

.wordlist.txt
README.md

Include new http-server-x509-svid-parser repository

---

.wordlist.txt
README.md

Include socat-tang-filter

---

.wordlist.txt
README.md

Include contributions to keylime-agent

---

README.md

Order lists alphabetically

---

README.md

Fix keylime-rust section

---

README.md

Set correct tang-operator test suite link

---

README.md

Add associate professor information

---

README.md

Include python programming references

---

README.md

Update README.md to include URJC profile

---

README.md

Include test repositores

---

README.md

Include Fedora as Linux distribution I know about

---

README.md

Add reference to attestation-operator

---

README.md

Add Keylime repositories as important contribution

---

README.md

Specify Python as programming language I teach

---

README.md

Fix README.md to include article titles

---

.wordlist.txt
README.md

Include pkcs11-provider contributions

---

README.md

Fix README.md to include alphabetical order

---

README.md

Sort Rust section alphabetically

---

README.md

Update information related to Git knowledge

---

README.md

Add used languages pie chart

---

.wordlist.txt

Fix spellcheck issues

---

.github/workflows/auto-assign.yaml

Include auto-assign GH action
